baseURL: https://ryanwanglbsmfa.netlify.app/
languageCode: en-us
title: Portfolio website for Ryan Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A brief professional introduction of myself.
    title: I am Ryan Wang 王淏宇, a Chinese student at London Business School and future banker.
  blog: {}
  contact: 
    address:
      - city: London, England W2 1BH
        country: UK
        street: 12 Hermitage Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rwang.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0) 7743-345-209
        title: Phone
  custom_css: []
  custom_js: []
  description: Masters in Financial Analysis
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ryan
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#     - icon: fa-twitter
#       label: Twitter
#       url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/haoyu.wayne/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/ryan.h.wang/
      - icon: fa-github
        label: GitHub
        url: https://github.com/rwanglbsmfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/rwmfa2022/
  image: ''
  name: Ryan Wang
  navigation:
#    button1:
#      - name: Get Started
#        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Back to Homepage
        url: '#'
#      - name: Blogs
#        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By Ryan Wang
    title: Professional Website
  tiles:
    enable: yes
    showcase:
       - image: lbs.jpg
         subtitle: London Business School
         title: Education 
         url: blogs/lbs
       - image: resume.jpg
         subtitle: Investment Banking Recruitment
         title: My Resume
         url: blogs/resume
       - image: ph.jpg
#        subtitle: Lorem Etiam Nullam
         title: Professional Headshot
         url: blogs/ph
       - image: corporate.jpg
         subtitle: Past experience and future plans
         title: Career
         url: blogs/corporate
       - image: pic05.jpg
         subtitle: Risk and Return Analysis
         title: R Project
         url: blogs/risk_return
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
#    buttonText: Get Started
#    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
